-- Live source for workshop-nudge-agent (Internal Playground Snowflake):
--   GTM.ANALYTICS.ACCOUNTS
--
-- Stale-account logic uses:
--   IS_ACTIVE_ENTERPRISE_CUSTOMER = TRUE
--   last touch = COALESCE(LAST_ACTIVITY_BY_GO_TO_MARKET_AT, LAST_ACTIVITY_ON)
--   stale when null or >= :minDays old
--
-- Context notes/usage are derived from columns on the same table
-- (AE_NOTES, BOUNTY_NOTES, PLATFORM_TYPE, VRAY_FRAMEWORKS, etc.).
-- A dedicated workshop/events table can replace the activity proxy later.

-- Key columns (subset) from GTM.ANALYTICS.ACCOUNTS:
--   SFDC_ACCOUNT_ID
--   ACCOUNT_NAME
--   HIGHEST_BILLING_PLAN
--   ANNUAL_RECURRING_REVENUE
--   ACCOUNT_LIFECYCLE_STAGE
--   OWNER_NAME
--   CUSTOMER_SUCCESS_MANAGER_NAME
--   SALES_ENGINEER_NAME
--   TECHNICAL_CONSULTANT_NAME
--   ACCOUNT_LINK
--   AE_NOTES
--   LAST_ACTIVITY_ON
--   LAST_ACTIVITY_BY_GO_TO_MARKET_AT
--   IS_ACTIVE_ENTERPRISE_CUSTOMER
--   IS_INTERNAL_TEST
--   PLATFORM_TYPE
--   CURRENT_SOFTWARE_FRAMEWORK
--   VRAY_FRAMEWORKS
--   AVG_BUILDS_30D
--   SEAT_UTILIZATION
